name: florafind-backend
region: nyc
services:
  - name: api
    dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
    health_check:
      http_path: /
    routes:
      - path: /
    envs:
      - key: POSTGRES_SERVER
        scope: RUN_TIME
      - key: POSTGRES_USER
        scope: RUN_TIME
      - key: POSTGRES_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: POSTGRES_DB
        scope: RUN_TIME
      - key: POSTGRES_PORT
        scope: RUN_TIME
        value: '5432'
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ALGORITHM
        scope: RUN_TIME
        value: HS256
      - key: PLANTNET_API_URL
        scope: RUN_TIME
      - key: PLANTNET_API_KEY
        scope: RUN_TIME
        type: SECRET 